# Generated by Django 4.2.5 on 2023-09-29 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_employee_delete_product_delete_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="cpassword",
        ),
    ]
