# Generated by Django 4.2.5 on 2023-09-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_employee_cpassword"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_name", models.CharField(max_length=100)),
                ("date_of_receiving", models.DateField()),
                ("quantity", models.IntegerField()),
                ("w_o_n_o", models.IntegerField()),
            ],
        ),
    ]
