# Generated by Django 4.2.5 on 2023-09-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_materialin"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialin",
            name="challan",
            field=models.ImageField(default="industrylogo.jpg", upload_to="challan"),
        ),
    ]
